/* AUTO-GENERATED by tools/emit-regions-js.py from tools/regions.json --
   do not hand-edit; edit fleet/canonical/tools/regions.json + fleet-sync.py --apply,
   then re-run this emitter. Public fields only (see regions.json's own
   _field_notes for what each key means and why some fields are absent here).
   Consumed by js/nav.js (region strip), js/turner-network.js (office NAP),
   and every host-sniffing js/*.js file that used to hardcode a site list. */
window.TURNER_REGIONS = {
  "avalon": {
    "domain": "https://avalonrealestate.ca",
    "label": "Avalon",
    "nav_label": "Avalon",
    "office": {
      "address": "St. John's, NL",
      "email": "cmorrison@royallepage.ca",
      "name": "Royal LePage Turner Realty (Avalon)",
      "phone": "709-725-6520"
    },
    "office_key": "avalon",
    "operator": "turner",
    "order": 2,
    "postal_prefixes": [
      "A1A",
      "A1B",
      "A1C",
      "A1E",
      "A1G",
      "A1H",
      "A1K",
      "A1L",
      "A1M",
      "A1N",
      "A1S",
      "A1W",
      "A1X",
      "A1Y",
      "A1Z",
      "A0A",
      "A0B"
    ],
    "r2_slug": "avalon",
    "repo_dir": "stjohns-site",
    "routes": {
      "home": "/",
      "listings": "/listings/",
      "market": "/pages/stjohns-mls-market-stats.html",
      "sell": "/pages/sell-your-home.html"
    },
    "site_id": "avalonrealestate",
    "site_key": "avalon",
    "state": "live",
    "territory": "avalon",
    "towns": [
      "St. John's",
      "Mount Pearl",
      "Conception Bay South",
      "Paradise",
      "Torbay",
      "Portugal Cove-St. Philip's",
      "Holyrood",
      "Bay Bulls",
      "Southern Shore"
    ]
  },
  "burin-south-coast": {
    "domain": null,
    "label": "Burin Peninsula & South Coast",
    "nav_label": "Burin Peninsula",
    "office": null,
    "office_key": null,
    "operator": null,
    "order": 7,
    "postal_prefixes": [
      "A0E"
    ],
    "r2_slug": null,
    "repo_dir": null,
    "routes": null,
    "site_id": null,
    "site_key": null,
    "state": "recruiting",
    "territory": "burin-south-coast",
    "towns": [
      "Marystown",
      "Burin",
      "Grand Bank",
      "Fortune",
      "St. Lawrence"
    ]
  },
  "clarenville": {
    "domain": null,
    "label": "Clarenville & Random Island",
    "nav_label": "Clarenville",
    "office": null,
    "office_key": null,
    "operator": null,
    "order": 6,
    "postal_prefixes": [
      "A0E"
    ],
    "r2_slug": null,
    "repo_dir": null,
    "routes": null,
    "site_id": null,
    "site_key": null,
    "state": "recruiting",
    "territory": "clarenville",
    "towns": [
      "Clarenville",
      "Random Island",
      "Shoal Harbour",
      "Bonavista Bay South"
    ]
  },
  "corner-brook-west-coast": {
    "domain": "https://royallepagenlrealty.ca",
    "label": "Corner Brook & West Coast",
    "nav_label": "Corner Brook",
    "office": {
      "address": "104-29 Humber Road, Corner Brook, NL A2H 1E3",
      "name": "Royal LePage NL Realty, Brokerage (Independently owned and operated)",
      "phone": "709-634-4444"
    },
    "office_key": null,
    "operator": "peer",
    "order": 5,
    "postal_prefixes": [
      "A2H"
    ],
    "r2_slug": null,
    "repo_dir": null,
    "routes": null,
    "site_id": null,
    "site_key": null,
    "state": "live",
    "territory": "corner-brook-west-coast",
    "towns": [
      "Corner Brook",
      "Deer Lake",
      "Stephenville",
      "Pasadena"
    ]
  },
  "gander": {
    "domain": "https://realestategander.com",
    "label": "Gander and Area",
    "nav_label": "Gander and Area",
    "office": {
      "address": "204 Airport Blvd, Gander, NL A1V 1L6",
      "email": "office@realestategander.com",
      "name": "Royal LePage Turner Realty",
      "phone": "709-256-7999"
    },
    "office_key": "gander",
    "operator": "turner",
    "order": 1,
    "postal_prefixes": [
      "A1V",
      "A0G"
    ],
    "r2_slug": "gander",
    "repo_dir": "realestategander-site",
    "routes": {
      "home": "/",
      "listings": "/listings/",
      "market": "/pages/gander-mls-market-stats.html",
      "sell": "/pages/sell-your-home.html"
    },
    "site_id": "realestategander",
    "site_key": "gander",
    "state": "live",
    "territory": "gander",
    "towns": [
      "Gander",
      "Gander Bay",
      "Appleton",
      "Glenwood",
      "Gambo",
      "Glovertown",
      "Lewisporte",
      "Twillingate",
      "Eastport Peninsula",
      "Fogo Island",
      "Change Islands",
      "Notre Dame Bay"
    ]
  },
  "goosebay": {
    "domain": "https://goosebayrealestate.ca",
    "label": "Labrador",
    "nav_label": "Labrador",
    "office": {
      "address": "371 Hamilton River Road, Suite 102, Happy Valley-Goose Bay, NL A0P 1C0",
      "email": "goosebay@royallepage.ca",
      "name": "Royal LePage Turner Realty (Happy Valley-Goose Bay)",
      "phone": "709-896-5001"
    },
    "office_key": "goosebay",
    "operator": "turner",
    "order": 3,
    "postal_prefixes": [
      "A0P"
    ],
    "r2_slug": "goosebay",
    "repo_dir": "goosebay-site",
    "routes": {
      "home": "/",
      "listings": "/listings/",
      "market": "/pages/market-stats.html",
      "sell": "/pages/sell-your-home.html"
    },
    "site_id": "goosebayrealestate",
    "site_key": "goosebay",
    "state": "live",
    "territory": "goosebay",
    "towns": [
      "Happy Valley-Goose Bay",
      "North West River"
    ]
  },
  "grand-falls-windsor": {
    "domain": "https://generationrealty.ca",
    "label": "Grand Falls-Windsor & Central",
    "nav_label": "Grand Falls",
    "office": {
      "address": "28 Cromer Avenue, Grand Falls-Windsor, NL",
      "name": "Royal LePage Generation Realty",
      "phone": "709-489-7000"
    },
    "office_key": null,
    "operator": "peer",
    "order": 4,
    "postal_prefixes": [
      "A2A"
    ],
    "r2_slug": null,
    "repo_dir": null,
    "routes": null,
    "site_id": null,
    "site_key": null,
    "state": "live",
    "territory": "grand-falls-windsor",
    "towns": [
      "Grand Falls-Windsor",
      "Bishop's Falls",
      "Botwood",
      "Badger & Buchans",
      "Norris Arm",
      "Springdale & South Brook",
      "Baie Verte",
      "Bay D'Espoir & Harbour Breton"
    ]
  },
  "labrador-city": {
    "domain": "https://labwestrealty.com",
    "label": "Labrador West",
    "nav_label": "Labrador West",
    "office": null,
    "office_key": "labwest",
    "operator": "turner",
    "order": 9,
    "postal_prefixes": [
      "A2V"
    ],
    "r2_slug": null,
    "repo_dir": "labwestrealty-site",
    "routes": null,
    "site_id": null,
    "site_key": "labwest",
    "state": "recruiting",
    "territory": "labrador-city",
    "towns": [
      "Labrador City",
      "Wabush"
    ]
  },
  "northern-peninsula": {
    "domain": null,
    "label": "Northern Peninsula",
    "nav_label": "Northern Peninsula",
    "office": null,
    "office_key": null,
    "operator": null,
    "order": 8,
    "postal_prefixes": [
      "A0K"
    ],
    "r2_slug": null,
    "repo_dir": null,
    "routes": null,
    "site_id": null,
    "site_key": null,
    "state": "recruiting",
    "territory": "northern-peninsula",
    "towns": [
      "St. Anthony",
      "Port Saunders",
      "Rocky Harbour"
    ]
  }
};
window.TURNER_SITE_KEY = window.TURNER_SITE_KEY || "hub";
