#!/usr/bin/env python3
"""
emit-regions-js.py — writes js/regions-data.js, the browser-side twin of
tools/regions.json (fleet-canonical, Tier-1 verbatim; this script is too).

Fleet review Part C (2026-09-08): tools/regions.json had zero code consumers
as of Slice 1. This is the first one — it turns the registry into a runtime
global every page can read without an extra fetch (regions.json itself
404s from a browser: `_redirects` blocks `/tools/*` on every site).

ONE FILE, FIVE SITES (Convention #15): site identity comes from
tools/_fleet_config.json's own site_key field (present on all 5 sites as of
Slice 1 — gander/avalon/goosebay/hub/labwest), NOT a hardcoded folder-name
dict. Adding a 6th hardcoded site-name map here would be exactly the
vocabulary drift this whole registry effort exists to kill.

Output shape: window.TURNER_REGIONS = { "<territory>": {...}, ... } — PUBLIC
fields only (key, label, nav_label, state, operator, domain, site_id,
r2_slug, office_key, postal_prefixes, towns, order, office). office
(name/address/phone/email) is included — it's genuine public NAP, already
rendered in plaintext in every site's footer, not a confidentiality
concern. Deliberately excludes roster (agent slugs — not needed
client-side, community-agent-map.json already covers Gander's per-community
agent cards) and the internal-only fields (repo_dir, site_key,
market_region_keys, _provenance, _note) — those stay in the source JSON for
build-time/server-side consumers to import directly (see
netlify/functions/lead-receive.ts's `import sourceRegistry from
'../../tools/lead_source_registry.json'` for the precedent this follows).

Convention #74 fail-safe: missing/unparseable regions.json -> loud stderr
warning + exit 1 WITHOUT writing (so a previously-committed regions-data.js
is never silently replaced by nothing). No sweep, no listing data touched —
this is safe to run locally at any time, unlike ddf-generate-pages.py.

Usage:
  python3 tools/emit-regions-js.py                 # writes js/regions-data.js
  python3 tools/emit-regions-js.py --check          # exit 1 if stale, no write
  python3 tools/emit-regions-js.py --dry-run         # print, don't write
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SITE_ROOT = SCRIPT_DIR.parent
REGIONS_PATH = SCRIPT_DIR / "regions.json"
FLEET_CONFIG_PATH = SCRIPT_DIR / "_fleet_config.json"
OUT_PATH = SITE_ROOT / "js" / "regions-data.js"

PUBLIC_FIELDS = [
    "territory", "label", "nav_label", "state", "operator", "domain",
    "site_id", "r2_slug", "office_key", "postal_prefixes", "towns", "order",
    # office (name/address/phone/email) is genuine public NAP -- already
    # rendered in plaintext in every site's footer -- not a confidentiality
    # concern like roster (agent slugs) or the internal join keys below.
    "office",
    # repo_dir (e.g. "realestategander-site") is just a folder name, already
    # visible in agent_roster.json's home_site field and needed client-side
    # by js/agent-cma.js's R2_MARKET/SITE_DOMAIN lookup (keyed by repo dir,
    # the vocabulary agent_roster.json's roster entries carry).
    "repo_dir",
    # site_key (fleet review Part C, Slice 3, 2026-09-09): the
    # _fleet_config.json value window.TURNER_SITE is actually set to.
    # Territory (this dict's own key) and site_key are the SAME string for
    # every live Turner region today (gander/avalon/goosebay) but NOT for
    # labrador-city, whose territory key is "labrador-city" while its
    # site_key (and TURNER_SITE) is "labwest" -- js/nav.js must resolve
    # "the region matching window.TURNER_SITE" via this field, never via
    # TURNER_REGIONS[window.TURNER_SITE] directly, or Labrador West (and the
    # hub) silently fail every lookup keyed on the current site.
    "site_key",
    # routes (fleet review Part C, Slice 3, 2026-09-09): page-kind -> path,
    # live+turner regions only. js/nav.js reads this to send a visitor
    # hopping regions to the same kind of page on the destination rather
    # than always the homepage.
    "routes",
]


def build_public_regions(data: dict) -> dict:
    out = {}
    for key, region in (data.get("regions") or {}).items():
        out[key] = {f: region.get(f) for f in PUBLIC_FIELDS}
    return out


def render(public_regions: dict, site_key: str) -> str:
    payload = json.dumps(public_regions, indent=2, ensure_ascii=False, sort_keys=True)
    return (
        "/* AUTO-GENERATED by tools/emit-regions-js.py from tools/regions.json --\n"
        "   do not hand-edit; edit fleet/canonical/tools/regions.json + fleet-sync.py --apply,\n"
        "   then re-run this emitter. Public fields only (see regions.json's own\n"
        "   _field_notes for what each key means and why some fields are absent here).\n"
        "   Consumed by js/nav.js (region strip), js/turner-network.js (office NAP),\n"
        "   and every host-sniffing js/*.js file that used to hardcode a site list. */\n"
        f"window.TURNER_REGIONS = {payload};\n"
        f"window.TURNER_SITE_KEY = window.TURNER_SITE_KEY || {json.dumps(site_key)};\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the on-disk file is stale, never write")
    ap.add_argument("--dry-run", action="store_true", help="print the output, don't write")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    if not REGIONS_PATH.exists():
        print(f"[emit-regions-js] ERROR: {REGIONS_PATH} missing -- refusing to write", file=sys.stderr)
        return 1
    try:
        data = json.loads(REGIONS_PATH.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"[emit-regions-js] ERROR: {REGIONS_PATH} unparseable: {exc}", file=sys.stderr)
        return 1

    site_key = "unknown"
    if FLEET_CONFIG_PATH.exists():
        try:
            site_key = json.loads(FLEET_CONFIG_PATH.read_text(encoding="utf-8")).get("site_key", "unknown")
        except Exception as exc:
            print(f"[emit-regions-js] WARNING: {FLEET_CONFIG_PATH} unparseable ({exc}); site_key left 'unknown'", file=sys.stderr)
    else:
        print(f"[emit-regions-js] WARNING: {FLEET_CONFIG_PATH} missing; site_key left 'unknown'", file=sys.stderr)

    public_regions = build_public_regions(data)
    if not public_regions:
        print("[emit-regions-js] ERROR: 0 regions in regions.json -- refusing to write an empty file", file=sys.stderr)
        return 1

    new_text = render(public_regions, site_key)

    if args.check:
        old_text = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else None
        if old_text == new_text:
            if args.verbose:
                print(f"[emit-regions-js] OK -- {OUT_PATH} is current ({len(public_regions)} region(s))")
            return 0
        print(f"[emit-regions-js] STALE -- {OUT_PATH} does not match regions.json", file=sys.stderr)
        return 1

    if args.dry_run:
        print(new_text)
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if OUT_PATH.exists() and OUT_PATH.read_text(encoding="utf-8") == new_text:
        if args.verbose:
            print(f"[emit-regions-js] unchanged -- {OUT_PATH} ({len(public_regions)} region(s))")
        return 0
    OUT_PATH.write_text(new_text, encoding="utf-8")
    print(f"[emit-regions-js] wrote {OUT_PATH} ({len(public_regions)} region(s), site_key={site_key!r})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
